### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by pdewouters** [humanmade/debug-bar-elasticpress#4]
```
[07-Jul-2020 12:54:57 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ep_is_indexing() in /usr/src/app/vendor/humanmade/debug-bar-elasticpress/classes/class-ep-debug-bar-elasticpress.php:223
Stack trace:
#0 /usr/src/app/vendor/humanmade/debug-bar-elasticpress/classes/class-ep-debug-bar-elasticpress.php(46): EP_Debug_Bar_ElasticPress->display_debugging_info()
#1 /usr/src/app/vendor/johnbillion/query-monitor/collectors/debug_bar.php(34): EP_Debug_Bar_ElasticPress->render()
#2 /usr/src/app/vendor/johnbillion/query-monitor/output/html/debug_bar.php(40): QM_Collector_Debug_Bar->render()
#3 /usr/src/app/vendor/johnbillion/query-monitor/dispatchers/Html.php(222): QM_Output_Html_Debug_Bar->output()
#4 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(287): QM_Dispatcher_Html->dispatch('')
#5 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#6 /usr/src/app/wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /usr/src/app/wordpress/wp-includes/load.php(960): do_action('shutdown')
#8 [internal function]: shutdown_action_hook()
#9 {main}
  thrown in /usr/src/app/vendor/humanmade/debug-bar-elasticpress/classes/class-ep-debug-bar-elasticpress.php on line 223
```

**Comment by roborourke** [comment]
I think was fixed in #5 - ElasticPress v3 removed the `ep_is_indexing()` function.
